# Generated by Django 5.2.3 on 2025-06-28 11:44

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=api.models.generate_order_number, editable=False, max_length=20, unique=True, verbose_name='订单号')),
                ('phone_number', models.CharField(max_length=15, verbose_name='用户手机号')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('PRINTING', '打印中'), ('COMPLETED', '已完成'), ('PICKED_UP', '已取件'), ('CANCELLED', '已取消')], default='PENDING', max_length=10, verbose_name='订单状态')),
                ('specifications', models.JSONField(verbose_name='打印规格')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='订单总价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='PrintFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='print_files/%Y/%m/%d/', verbose_name='上传的文件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.order', verbose_name='所属订单')),
            ],
        ),
    ]
