# Generated by Django 5.2.3 on 2025-07-16 09:56

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BindingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_type', models.CharField(default='none', help_text='装订方式', max_length=50)),
                ('binding_cost', models.DecimalField(decimal_places=2, default=0, help_text='此组的装订费用', max_digits=10)),
                ('sequence_in_order', models.PositiveIntegerField(default=0, help_text='组在订单中的顺序')),
            ],
            options={
                'ordering': ['sequence_in_order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=api.models.generate_order_number, help_text='时间戳订单号', max_length=20, unique=True)),
                ('pickup_code', models.CharField(blank=True, help_text='循环取件码 (P-XXX)', max_length=10)),
                ('pickup_code_num', models.IntegerField(default=0, help_text='用于排序的取件码数字部分')),
                ('phone_number', models.CharField(blank=True, help_text='顾客联系电话', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='订单总价', max_digits=10)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', help_text='订单状态', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='支付方式', max_length=50, null=True)),
                ('payment_screenshot', models.FileField(blank=True, help_text='支付凭证截图', null=True, upload_to='payments/')),
                ('order_summary_pdf', models.FileField(blank=True, help_text='订单摘要PDF', null=True, upload_to='summaries/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(help_text='文件存储路径', upload_to='order_documents/')),
                ('color_mode', models.CharField(default='black_white', help_text='色彩模式', max_length=20)),
                ('print_sided', models.CharField(default='single', help_text='单双面', max_length=20)),
                ('copies', models.PositiveIntegerField(default=1, help_text='打印份数')),
                ('page_count', models.PositiveIntegerField(help_text='文件页数')),
                ('print_cost', models.DecimalField(decimal_places=2, help_text='此文件的打印费用', max_digits=10)),
                ('sequence_in_group', models.PositiveIntegerField(default=0, help_text='文件在组内的顺序')),
                ('group', models.ForeignKey(help_text='所属装订组', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.bindinggroup')),
            ],
            options={
                'ordering': ['sequence_in_group'],
            },
        ),
        migrations.AddField(
            model_name='bindinggroup',
            name='order',
            field=models.ForeignKey(help_text='所属订单', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.order'),
        ),
    ]
