# Generated by Django on 2025-09-20
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_avatar_url_user_github_id_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='page_count_source',
            field=models.CharField(
                choices=[('estimated', '预估'), ('exact', '精确')],
                default='estimated',
                help_text='页数来源（预估/精确）',
                max_length=16,
            ),
        ),
    ]
