# Generated by Django 5.2.3 on 2025-06-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_printfile_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/%Y/%m/%d/', verbose_name='付款截图'),
        ),
    ]
