# Generated by Django 5.2.3 on 2025-10-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document_page_count_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='paper_size',
            field=models.CharField(choices=[('a4', 'A4'), ('b5', 'B5'), ('a4_70g', 'A4(70g)'), ('a4_80g', 'A4(80g)'), ('b5_70g', 'B5(70g)')], default='a4_70g', help_text='纸张尺寸', max_length=10),
        ),
    ]
