# Generated by Django 5.2.3 on 2025-06-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_payment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfile',
            name='purpose',
            field=models.CharField(choices=[('PRINT', '打印文件'), ('PAYMENT', '付款凭证')], default='PRINT', max_length=10, verbose_name='文件用途'),
        ),
    ]
