# Generated by Django 5.2.3 on 2025-11-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_document_paper_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remark',
            field=models.TextField(blank=True, help_text='用户备注', null=True),
        ),
    ]
