# Generated by Django 5.2.3 on 2025-07-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_printfile_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='取件码'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_code_num',
            field=models.IntegerField(default=0, verbose_name='取件码数字部分'),
        ),
    ]
