# Generated by Django 5.2.3 on 2025-11-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_remark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'completed'])), fields=('pickup_code',), name='unique_active_pickup_code'),
        ),
    ]
