# Generated by Django 5.2.3 on 2025-07-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_pickup_code_order_pickup_code_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_summary_pdf',
            field=models.FileField(blank=True, null=True, upload_to='order_summaries/%Y/%m/%d/', verbose_name='订单详情PDF'),
        ),
    ]
