# Generated by Django 5.2.3 on 2025-07-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_order_summary_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('WECHAT', '微信支付'), ('ALIPAY', '支付宝')], default='WECHAT', max_length=10, verbose_name='支付方式'),
        ),
    ]
