# Generated by Django 5.2.3 on 2025-12-04 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_options_order_unique_active_pickup_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="套餐名称，如'基础版'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='套餐描述')),
                ('pages', models.IntegerField(help_text='包含的标准打印页数')),
                ('price', models.DecimalField(decimal_places=2, help_text='套餐价格', max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='原价（用于显示优惠）', max_digits=10, null=True)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=100, help_text='折扣率（如95表示95折）', max_digits=5)),
                ('validity_days', models.IntegerField(blank=True, help_text='有效期（天数），空表示永久有效', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='是否启用该套餐')),
                ('is_featured', models.BooleanField(default=False, help_text='是否推荐套餐（在列表中突出显示）')),
                ('sort_order', models.IntegerField(default=0, help_text='排序权重（越小越靠前）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '打印套餐',
                'verbose_name_plural': '打印套餐',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='page_balance',
            field=models.IntegerField(default=0, help_text='账户页数余额（标准页数）'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_pages_purchased',
            field=models.IntegerField(default=0, help_text='累计购买页数'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_pages_used',
            field=models.IntegerField(default=0, help_text='累计使用页数'),
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='实际支付价格', max_digits=10)),
                ('pages_total', models.IntegerField(help_text='套餐总页数')),
                ('pages_remaining', models.IntegerField(help_text='剩余页数')),
                ('payment_method', models.CharField(blank=True, help_text='支付方式', max_length=50, null=True)),
                ('payment_screenshot', models.FileField(blank=True, help_text='支付凭证', null=True, upload_to='package_payments/')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, help_text='购买时间')),
                ('activated_at', models.DateTimeField(blank=True, help_text='激活时间（审核通过后）', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='过期时间', null=True)),
                ('status', models.CharField(choices=[('pending', '待支付'), ('active', '使用中'), ('expired', '已过期'), ('exhausted', '已用完'), ('cancelled', '已取消')], default='pending', help_text='套餐状态', max_length=20)),
                ('remark', models.TextField(blank=True, help_text='备注信息', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(help_text='套餐类型', on_delete=django.db.models.deletion.PROTECT, to='api.package')),
                ('user', models.ForeignKey(help_text='购买用户', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户套餐',
                'verbose_name_plural': '用户套餐',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('recharge', '充值'), ('consume', '消费'), ('refund', '退款'), ('admin_adjust', '管理员调整')], help_text='交易类型', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='交易金额', max_digits=10)),
                ('pages', models.IntegerField(help_text='页数变动（正数表示增加，负数表示减少）')),
                ('balance_before', models.IntegerField(help_text='交易前余额')),
                ('balance_after', models.IntegerField(help_text='交易后余额')),
                ('description', models.TextField(blank=True, help_text='交易描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, help_text='关联订单（如果是消费）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.order')),
                ('user', models.ForeignKey(help_text='关联用户', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('user_package', models.ForeignKey(blank=True, help_text='关联套餐（如果是充值）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.userpackage')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
