# Generated by Django 5.2.3 on 2025-07-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfile',
            name='page_calculation_status',
            field=models.CharField(choices=[('PENDING', '待计算'), ('PROCESSING', '计算中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='页数计算状态'),
        ),
        migrations.AddField(
            model_name='printfile',
            name='pages',
            field=models.IntegerField(default=0, verbose_name='文件页数'),
        ),
    ]
