# Generated by Django 5.2.3 on 2025-12-05 05:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_package_user_page_balance_user_total_pages_purchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='payment_screenshot',
            field=models.FileField(blank=True, help_text='支付凭证', null=True, upload_to=api.models.get_package_payment_path),
        ),
    ]
