# Generated by Django 5.2.3 on 2026-01-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_options_order_unique_active_pickup_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, help_text='是否营业。关闭时显示暂停营业页面')),
                ('closure_reason', models.CharField(default='放假暂停营业，感谢您的理解！', help_text='营业关闭时显示的原因描述', max_length=500)),
                ('reopening_date', models.DateField(blank=True, help_text='预计重新营业日期', null=True)),
                ('notice_content', models.TextField(blank=True, help_text='在关闭页面中显示的额外提示信息')),
                ('allow_viewing_history', models.BooleanField(default=True, help_text='关闭营业后，是否允许用户查看历史订单')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
    ]
